[package]
name = "curve-search"
version = "0.1.0"
authors = ["Izaak Meckler <ihmeckler@gmail.com>"]
edition = "2018"

[dependencies]
rug = "1.3.0"
reikna = "0.6.0"
primal = "0.2"
quadratic = "0.3.1"
integer-sqrt = "0.1.2"
rayon = "1.0.3"
